apiVersion : apps/v1
kind: Deployment
metadata:
  name: testvintedisafosswebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testvintedisafosswebapp
  template:
    metadata:
      labels:
        app: testvintedisafosswebapp 
    spec:
      containers:
        - name: testvintedisafosswebapp 
          image: isafoss.azurecr.io/testvintedisafosswebapp
          ports:
          - containerPort: 3000
          env:
          - name: AUTH_OKTA_ISSUER
            value: __AUTH_OKTA_ISSUER_VALUE__
          - name: AUTH_OKTA_CLIENT_ID
            value: __AUTH_OKTA_CLIENT_ID_VALUE__
