apiVersion : apps/v1
kind: Deployment
metadata:
  name: isafosswebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isafosswebapp
  template:
    metadata:
      labels:
        app: isafosswebapp 
    spec:
      containers:
        - name: isafosswebapp 
          image: isafoss.azurecr.io/isafosswebapp
          ports:
          - containerPort: 3000